// Feature: disney-world-tracker, Property 26: incremental mean_x10 equals reference recompute and threshold/privacy hold
/**
 * Property-based tests for the Aggregate_Ratings_Service incremental update.
 *
 * Validates: Requirements 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.8, 10.9, 10.10
 *
 * The Aggregate_Ratings_Service maintains per-Experience state as a triple
 * `(sum_ratings, count_ratings, mean_x10)` and advances it incrementally on
 * each `RatingChanged{oldValue, newValue}` event rather than recomputing from
 * scratch. Design Property 26 says, in essence:
 *
 *   For any sequence of `set(user, value)`, `replace(user, value)`, and
 *   `remove(user)` operations against a single Experience, the incremental
 *   triple obtained by chaining `updateMeanX10` event-by-event must equal
 *   the triple obtained by recomputing from scratch over the resulting raw
 *   rating set; `mean_x10` is `null` iff `count < 3`; when non-null,
 *   `mean_x10` is in `[10, 100]`; and the `AggregateRatingDTO` response
 *   shape exposes only `value` and `count`.
 *
 * Each `fc.assert` runs with `numRuns: 100` per the spec convention. Events
 * are generated by a small state-machine arbitrary that respects the
 * preconditions of each operation (R10.8: replace targets an existing
 * rating; R10.9: remove targets an existing rating); the model maps
 * `userId -> rating` and is the source of truth for the from-scratch
 * recompute used as the test oracle.
 */

import { describe, expect, it } from 'vitest';
import fc from 'fast-check';

import type { AggregateRatingDTO } from '@dwt/shared';

import {
  MIN_AGGREGATE_RATING_COUNT,
  roundHalfUp,
  updateMeanX10,
  type AggregateMeanX10State,
} from '../updateMeanX10.js';

const NUM_RUNS = 100;

/**
 * Operation kinds applied during a generated sequence. Each maps to one
 * `RatingChanged` event with a specific `(oldValue, newValue)` shape:
 *
 *   - `set`     → `(null, newValue)`        — first rating by this user.
 *   - `replace` → `(oldValue, newValue)`    — user changes their rating.
 *   - `remove`  → `(oldValue, null)`        — user retracts their rating.
 */
type Op =
  | { readonly kind: 'set'; readonly userId: number; readonly value: number }
  | { readonly kind: 'replace'; readonly userId: number; readonly value: number }
  | { readonly kind: 'remove'; readonly userId: number };

/** Ratings are integers in `[1, 10]` (R4 — Tracking_Service contract). */
const ratingValueArb = fc.integer({ min: 1, max: 10 });

/**
 * Generate a sequence of operations that respects the preconditions of each
 * op against a running in-memory model `userId -> rating`. The generator
 * draws from a small bounded user pool so that `set`, `replace`, and
 * `remove` all become reachable along realistic interleavings.
 */
function operationSequence(
  maxOps: number,
  userPoolSize: number,
): fc.Arbitrary<readonly Op[]> {
  return fc
    .array(
      fc.record({
        userId: fc.integer({ min: 0, max: userPoolSize - 1 }),
        value: ratingValueArb,
        // Bias: when the user has a rating, choose between replace/remove;
        // when the user has no rating, only `set` is reachable.
        action: fc.constantFrom('set', 'replace', 'remove'),
      }),
      { minLength: 0, maxLength: maxOps },
    )
    .map((draws) => {
      const model = new Map<number, number>();
      const ops: Op[] = [];
      for (const draw of draws) {
        const has = model.has(draw.userId);
        if (!has) {
          // Only `set` is valid; coerce.
          model.set(draw.userId, draw.value);
          ops.push({ kind: 'set', userId: draw.userId, value: draw.value });
          continue;
        }
        if (draw.action === 'remove') {
          model.delete(draw.userId);
          ops.push({ kind: 'remove', userId: draw.userId });
        } else {
          // Treat both `set` and `replace` as `replace` when a rating exists,
          // since `set` after an existing rating is logically a replacement.
          model.set(draw.userId, draw.value);
          ops.push({ kind: 'replace', userId: draw.userId, value: draw.value });
        }
      }
      return ops;
    });
}

/**
 * Reference (from-scratch) recompute. Mirrors the design's storage row
 * formula directly so that any drift in `updateMeanX10` is caught by the
 * equivalence property below.
 */
function recomputeFromScratch(model: ReadonlyMap<number, number>): AggregateMeanX10State {
  let sum = 0;
  let count = 0;
  for (const value of model.values()) {
    sum += value;
    count += 1;
  }
  const meanX10 =
    count >= MIN_AGGREGATE_RATING_COUNT ? roundHalfUp(sum * 10, count) : null;
  return { sum, count, meanX10 };
}

/**
 * Apply an Op against an in-memory model and return the incremental event
 * `(oldValue, newValue)` to feed into `updateMeanX10`.
 */
function applyOp(
  model: Map<number, number>,
  op: Op,
): { oldValue: number | null; newValue: number | null } {
  switch (op.kind) {
    case 'set': {
      const oldValue = model.get(op.userId) ?? null;
      model.set(op.userId, op.value);
      return { oldValue, newValue: op.value };
    }
    case 'replace': {
      const oldValue = model.get(op.userId) ?? null;
      model.set(op.userId, op.value);
      return { oldValue, newValue: op.value };
    }
    case 'remove': {
      const oldValue = model.get(op.userId) ?? null;
      model.delete(op.userId);
      return { oldValue, newValue: null };
    }
  }
}

describe('Aggregate_Ratings_Service — Property 26: incremental vs reference recompute', () => {
  it('chained updateMeanX10 equals from-scratch recompute over the resulting raw set', () => {
    fc.assert(
      fc.property(operationSequence(50, 8), (ops) => {
        const model = new Map<number, number>();
        let state: AggregateMeanX10State = { sum: 0, count: 0, meanX10: null };

        for (const op of ops) {
          const { oldValue, newValue } = applyOp(model, op);
          state = updateMeanX10(state.sum, state.count, oldValue, newValue);

          // Invariant after every event: incremental == reference recompute.
          const reference = recomputeFromScratch(model);
          if (
            state.sum !== reference.sum ||
            state.count !== reference.count ||
            state.meanX10 !== reference.meanX10
          ) {
            return false;
          }
        }
        return true;
      }),
      { numRuns: NUM_RUNS },
    );
  });

  it('threshold gating: meanX10 is null iff count < MIN_AGGREGATE_RATING_COUNT (R10.4)', () => {
    fc.assert(
      fc.property(operationSequence(50, 8), (ops) => {
        const model = new Map<number, number>();
        let state: AggregateMeanX10State = { sum: 0, count: 0, meanX10: null };

        for (const op of ops) {
          const { oldValue, newValue } = applyOp(model, op);
          state = updateMeanX10(state.sum, state.count, oldValue, newValue);

          const belowThreshold = state.count < MIN_AGGREGATE_RATING_COUNT;
          const isNull = state.meanX10 === null;
          if (belowThreshold !== isNull) {
            return false;
          }
        }
        return true;
      }),
      { numRuns: NUM_RUNS },
    );
  });

  it('non-null mean_x10 is in [10, 100] (R10.1: rendered value in [1.0, 10.0])', () => {
    fc.assert(
      fc.property(operationSequence(50, 8), (ops) => {
        const model = new Map<number, number>();
        let state: AggregateMeanX10State = { sum: 0, count: 0, meanX10: null };

        for (const op of ops) {
          const { oldValue, newValue } = applyOp(model, op);
          state = updateMeanX10(state.sum, state.count, oldValue, newValue);

          if (state.meanX10 !== null) {
            if (state.meanX10 < 10 || state.meanX10 > 100) {
              return false;
            }
          }
        }
        return true;
      }),
      { numRuns: NUM_RUNS },
    );
  });

  it('count never goes negative regardless of operation interleaving (R10.2)', () => {
    fc.assert(
      fc.property(operationSequence(50, 8), (ops) => {
        const model = new Map<number, number>();
        let state: AggregateMeanX10State = { sum: 0, count: 0, meanX10: null };

        for (const op of ops) {
          const { oldValue, newValue } = applyOp(model, op);
          state = updateMeanX10(state.sum, state.count, oldValue, newValue);
          if (state.count < 0 || state.sum < 0) {
            return false;
          }
        }
        return true;
      }),
      { numRuns: NUM_RUNS },
    );
  });
});

describe('AggregateRatingDTO — Property 26 privacy boundary (R10.10)', () => {
  /**
   * Compile-time assertion that `AggregateRatingDTO` exposes EXACTLY the
   * fields `value` and `count`. If a future change adds a third field
   * (e.g., another User's rating) `Extra` becomes a non-empty union and
   * `assertNoExtraKeys` fails to typecheck. The test would fail to build,
   * which is the required behavior under R10.10.
   */
  type ExpectedKeys = 'value' | 'count';
  type Extra = Exclude<keyof AggregateRatingDTO, ExpectedKeys>;
  type Missing = Exclude<ExpectedKeys, keyof AggregateRatingDTO>;
  // Both must resolve to `never` for the privacy boundary to hold.
  const _assertNoExtraKeys: Extra extends never ? true : never = true;
  const _assertNoMissingKeys: Missing extends never ? true : never = true;
  void _assertNoExtraKeys;
  void _assertNoMissingKeys;

  it('the DTO shape produced from any aggregate state contains only `value` and `count`', () => {
    fc.assert(
      fc.property(operationSequence(30, 8), (ops) => {
        const model = new Map<number, number>();
        let state: AggregateMeanX10State = { sum: 0, count: 0, meanX10: null };
        for (const op of ops) {
          const { oldValue, newValue } = applyOp(model, op);
          state = updateMeanX10(state.sum, state.count, oldValue, newValue);
        }

        // Render the row to the API DTO at the boundary, exactly as the
        // route layer is required to (mean_x10 / 10 to one decimal, or
        // null below the threshold; count always present).
        const dto: AggregateRatingDTO = {
          value: state.meanX10 === null ? null : state.meanX10 / 10,
          count: state.count,
        };

        const keys = Object.keys(dto).sort();
        if (keys.length !== 2 || keys[0] !== 'count' || keys[1] !== 'value') {
          return false;
        }

        // Value, when present, must be in [1.0, 10.0] (R10.1, R10.5).
        if (dto.value !== null && (dto.value < 1 || dto.value > 10)) {
          return false;
        }
        // Count is always a non-negative integer (R10.3, R10.4).
        if (!Number.isInteger(dto.count) || dto.count < 0) {
          return false;
        }
        return true;
      }),
      { numRuns: NUM_RUNS },
    );
  });
});

describe('Aggregate_Ratings_Service — fixed regression examples', () => {
  it('threshold transition: third rating publishes the mean (R10.3, R10.4)', () => {
    let state: AggregateMeanX10State = { sum: 0, count: 0, meanX10: null };
    state = updateMeanX10(state.sum, state.count, null, 5);
    expect(state.meanX10).toBeNull();
    state = updateMeanX10(state.sum, state.count, null, 7);
    expect(state.meanX10).toBeNull();
    state = updateMeanX10(state.sum, state.count, null, 9);
    // sum = 21, count = 3, mean = 7.0 → mean_x10 = 70.
    expect(state).toEqual({ sum: 21, count: 3, meanX10: 70 });
  });

  it('replace excludes the prior value and includes the new one exactly once (R10.8)', () => {
    // Start with three ratings: 4, 6, 8 (sum=18, count=3, mean_x10=60).
    let state: AggregateMeanX10State = { sum: 0, count: 0, meanX10: null };
    state = updateMeanX10(state.sum, state.count, null, 4);
    state = updateMeanX10(state.sum, state.count, null, 6);
    state = updateMeanX10(state.sum, state.count, null, 8);
    expect(state).toEqual({ sum: 18, count: 3, meanX10: 60 });

    // User who rated 4 replaces with 10; sum=24, count=3, mean_x10=80.
    state = updateMeanX10(state.sum, state.count, 4, 10);
    expect(state).toEqual({ sum: 24, count: 3, meanX10: 80 });
  });

  it('remove excludes the rating from the aggregate (R10.9)', () => {
    let state: AggregateMeanX10State = { sum: 0, count: 0, meanX10: null };
    state = updateMeanX10(state.sum, state.count, null, 4);
    state = updateMeanX10(state.sum, state.count, null, 6);
    state = updateMeanX10(state.sum, state.count, null, 8);
    expect(state).toEqual({ sum: 18, count: 3, meanX10: 60 });

    // Removing the 8 drops back below threshold: meanX10 must become null.
    state = updateMeanX10(state.sum, state.count, 8, null);
    expect(state).toEqual({ sum: 10, count: 2, meanX10: null });
  });
});
