/**
 * PinView — renders a single collectible pin.
 *
 * Art strategy (spec task 8, "pre-bake"): the authoritative pin artwork is generated by the
 * reviewed catalogue renderer and snapshotted into `pinArt.ts` at build time; this component
 * renders that baked SVG with `react-native-svg`'s `SvgXml`. That keeps the catalogue generators
 * as the single source of truth (no client-side re-implementation of the firework/scene/weld
 * engine, so the two cannot drift) and faithfully reproduces every pin — including the bespoke
 * composite pins a hand-written renderer could not.
 *
 * Two presentation concerns are applied here at render time rather than baked in:
 *  - Locked state: the baked art is dimmed and a padlock badge is overlaid. (The catalogue's exact
 *    dead-ramp locked recolour is not baked to keep the art bundle to one variant; see PinView tests.)
 *  - Rarity shimmer: pearl/prism/mythic get a gentle looping glow (opacity pulse). The reference's
 *    CSS sweep cannot ride a baked blob and silhouette-clipping an arbitrary composite is not
 *    feasible, so this is a silhouette-agnostic glow. It honours reduce-motion and a `motion` flag.
 */
import React, { useEffect, useRef, useState } from 'react';
import { AccessibilityInfo, Animated, Pressable, StyleSheet, View } from 'react-native';
import { SvgXml } from 'react-native-svg';
import type { PinTier } from '@dwt/shared';

import { PIN_ART } from './pinArt';

/** Tiers that animate — motion is a rarity signal reserved for the top of the ladder. */
const SHIMMER_MS: Partial<Record<PinTier, number>> = {
  pearl: 5500, // slow glow
  prism: 2400, // fast pulse (the reference's sweep, approximated silhouette-agnostically)
  mythic: 3200, // bespoke capstone sheen
};

export interface PinViewProps {
  /** Pin id used to look up the baked art in `PIN_ART`. */
  readonly pinId?: string;
  /** Explicit baked SVG markup (overrides `pinId`; used by the detail view and tests). */
  readonly art?: string;
  readonly tier: PinTier;
  readonly unlocked: boolean;
  readonly size?: number;
  readonly onPress?: () => void;
  readonly testID?: string;
  readonly accessibilityLabel?: string;
  /** Enable the rarity glow for pearl/prism/mythic. Default true; set false on dense grids. */
  readonly motion?: boolean;
}

/** A small padlock badge drawn over locked pins. */
function LockBadge({ size }: { size: number }): React.ReactElement {
  const d = size * 0.34;
  return (
    <View
      style={[
        styles.lockBadge,
        { width: d, height: d, borderRadius: d / 2, top: (size - d) / 2, left: (size - d) / 2 },
      ]}
    >
      <SvgXml
        width={d * 0.62}
        height={d * 0.62}
        xml={
          '<svg viewBox="0 0 512 512"><path fill="#e7e0f5" fill-rule="evenodd" d="' +
          'M256 60 C196 60 148 108 148 168 V214 H120 A28 28 0 0 0 92 242 V430 A28 28 0 0 0 120 458 ' +
          'H392 A28 28 0 0 0 420 430 V242 A28 28 0 0 0 392 214 H364 V168 C364 108 316 60 256 60 Z ' +
          'M212 168 C212 144 232 124 256 124 C280 124 300 144 300 168 V214 H212 Z"/></svg>'
        }
      />
    </View>
  );
}

export function PinView({
  pinId,
  art,
  tier,
  unlocked,
  size = 120,
  onPress,
  testID,
  accessibilityLabel,
  motion = true,
}: PinViewProps): React.ReactElement {
  const svg = art ?? (pinId ? PIN_ART[pinId] : undefined);
  const label = accessibilityLabel ?? `${tier} pin${unlocked ? '' : ' (locked)'}`;

  const shimmerMs = SHIMMER_MS[tier];
  const animates = unlocked && motion && shimmerMs != null;

  const glow = useRef(new Animated.Value(1)).current;
  // null = not yet determined; we only start animating once we've confirmed motion is allowed,
  // so an enabled reduce-motion setting suppresses the glow from the very first frame.
  const [reduceMotion, setReduceMotion] = useState<boolean | null>(null);

  useEffect(() => {
    if (!animates) return undefined;
    let mounted = true;
    try {
      const p = AccessibilityInfo?.isReduceMotionEnabled?.();
      if (p && typeof (p as Promise<boolean>).then === 'function') {
        (p as Promise<boolean>)
          .then((v) => mounted && setReduceMotion(!!v))
          .catch(() => mounted && setReduceMotion(false));
      } else if (mounted) {
        setReduceMotion(false);
      }
    } catch {
      if (mounted) setReduceMotion(false);
    }
    return () => {
      mounted = false;
    };
  }, [animates]);

  useEffect(() => {
    if (!animates || reduceMotion !== false || shimmerMs == null) return undefined;
    const half = shimmerMs / 2;
    const loop = Animated.loop(
      Animated.sequence([
        Animated.timing(glow, { toValue: 0.78, duration: half, useNativeDriver: true }),
        Animated.timing(glow, { toValue: 1, duration: half, useNativeDriver: true }),
      ]),
    );
    loop.start();
    return () => loop.stop();
  }, [animates, reduceMotion, shimmerMs, glow]);

  const body = svg ? (
    <SvgXml
      xml={svg}
      width={size}
      height={size}
      opacity={unlocked ? 1 : 0.18}
      onError={() => undefined}
    />
  ) : (
    // fallback — should never occur for a real pin (pinArtGate.test enforces coverage)
    <View style={[styles.fallback, { width: size, height: size, borderRadius: size / 2 }]} />
  );

  const content = (
    <View style={{ width: size, height: size }}>
      {animates && reduceMotion === false ? (
        <Animated.View style={{ opacity: glow }}>{body}</Animated.View>
      ) : (
        body
      )}
      {!unlocked ? <LockBadge size={size} /> : null}
    </View>
  );

  if (onPress) {
    return (
      <Pressable onPress={onPress} testID={testID} accessibilityRole="button" accessibilityLabel={label}>
        {content}
      </Pressable>
    );
  }
  return (
    <View testID={testID} accessibilityRole="image" accessibilityLabel={label}>
      {content}
    </View>
  );
}

const styles = StyleSheet.create({
  fallback: { backgroundColor: 'rgba(255,255,255,0.06)' },
  lockBadge: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(20,16,34,0.82)',
  },
});

export default PinView;
